---
title: "Extraction of DFCs from expreimental data"
output:
  html_notebook:
    theme: united
    toc: yes
  html_document:
    df_print: paged
    theme: united
    toc: yes
  pdf_document: default
---


## Setup

```{r setup}
library(tidyverse)

scale_color <- viridis::scale_color_viridis()
discrete_color <- ggsci::scale_color_d3("category20")
```


## calassification & visualization

```{r classification}
quant <-  Normc[useg,][useg.30,][B$weight[-1]!=0,] %>% split(.,rownames(Normc[useg,][useg.30,][B$weight[-1]!=0,])) %>% 
  lapply(function(x){as_tibble(t(x)) %>% dplyr::mutate(cluster=Df$cluster)}) %>% 
  lapply(function(x){
    df <- x; colnames(df)[1] <- "value"
    group_by(df,cluster) %>% summarise("1st"=quantile(value)[2],
                                        "mean"=quantile(value)[3],
                                        "3rd"=quantile(value)[4],.groups='drop')
    })
groups <- vector("list",3)
names(groups) <- c("strong","weak","specific")
for (i in 1:length(quant)) {
  if(all(quant[[i]][,4] == 0)){
    groups[["specific"]] <- c(groups[["specific"]],names(quant)[i])
    }else{
      if(sum(quant[[i]][,4] > 0) < 3 && any(quant[[1]]$cluster[quant[[1]][,4] > 0] == POI)){
        groups[["strong"]] <- c(groups[["strong"]],names(quant)[i])
        }else{
          groups[["weak"]] <- c(groups[["weak"]],names(quant)[i])
        } 
    }
}

print(groups)
#lapply(groups, length)
```


```{r venn plot}
venn(list(nonDEGs=setdiff(dfcs,res$ext_gene),
          DFCspecific=groups$specific))
res[order(res$baseMean),] %>% mutate(baseMean_rank=1:nrow(res)) %>% filter(ext_gene %in% groups$specific)
intersect(setdiff(dfcs,res$ext_gene),groups$specific)
```


```{r box plot,fig.width=9, fig.height=8}
dfc.expr <- normc %>%
  inner_join(Wei,.,by="ext_gene") %>% 
  tidyr::gather(cell,expr,-(1:4)) %>% inner_join(Df,by="cell")
boxes <- function(x,nrow=5){
  dfc.expr %>%
    filter(ext_gene %in% x) %>%
    ggplot(aes(x=cluster,y=expr,fill=Target)) +
    geom_boxplot() + facet_wrap(~reorder(ext_gene,-abs(weight)),nrow=nrow) +
    theme_minimal() + discrete_color + 
    theme(axis.text.x = element_blank(),legend.position = 'none') 
}
1:3 %>% map(~boxes(groups[[.]][1:20]))
```


```{r GO enrichment, fig.width=8,fig.height=4}
entid <- bitr(e2g$ens_gene[e2g$ext_gene %in% groups$strong],fromType = "ENSEMBL",toType = "ENTREZID",org.Mm.eg.db) %>% .$ENTREZID
goen <- enrichGO(entid,OrgDb = org.Mm.eg.db,readable = TRUE,ont="BP") %>% clusterProfiler::simplify()
dotplot(goen)
```


```{r plot DFC specific, fig.width=10, fig.height=7}
lab.POI <- Df$cluster == POI

set.seed(10)
um.mini <- uwot::umap(t(normc[,-1][,lab.POI]),n_neighbors=30,min_dist=0.5,pca=50,n_threads = 16)
Df.mini <- Df %>% filter(lab.POI) %>% select(c(-UMAP1,-UMAP2)) %>% mutate(UMAP1=um.mini[,1],UMAP2=um.mini[,2],)
expr.spe <- Normc[rownames(Normc) %in% groups$specific,] %>% t 
biexpr.spe <- cbind(um.mini,(expr.spe[lab.POI,] >0 )) %>% as_tibble() %>% 
  rename(UMAP1=V1,UMAP2=V2) %>% gather(key="gene",value = "expression",-(1:2))

ggplot(biexpr.spe,aes(x=UMAP1,y=UMAP2,color=as.double(expression))) +
    geom_point(size=0.2,alpha=0.8) + facet_wrap(~gene,nrow = 4) +
    theme_dark() + coord_fixed() + scale_color
patchwork::wrap_plots(
  ggplot(Df.mini,aes(x=UMAP1,y=UMAP2,color=cell_annotation)) +geom_point(size=0.8,alpha=0.8) + theme_minimal() + coord_fixed() + discrete_color,
  ggplot(Df.mini,aes(x=UMAP1,y=UMAP2,color=injury)) +geom_point(size=0.8,alpha=0.8) + theme_minimal() + coord_fixed() + discrete_color,
  ggplot(Df.mini,aes(x=UMAP1,y=UMAP2,color=nUMI)) +geom_point(size=0.8,alpha=0.8) + theme_minimal() + coord_fixed() + scale_color,
  ggplot(Df.mini,aes(x=UMAP1,y=UMAP2,color=percent_mito)) +geom_point(size=0.8,alpha=0.8) + theme_minimal() + coord_fixed() + scale_color,
  ncol=2)
```

```{r plot strong, fig.width=12, fig.height=8}
expr.str <- Normc[rownames(Normc) %in% groups$strong,] %>% t 
expr.str <- cbind(um.mini,expr.str[lab.POI,]) %>% as_tibble() %>% rename(UMAP1=V1,UMAP2=V2) %>% gather(key="gene",value = "expression",-(1:2))
expr.str$expression[expr.str$expression > 2.5] <- 2.5 #upper limit = 2.5
ggplot(expr.str,aes(x=UMAP1,y=UMAP2,color=as.double(expression))) +
  geom_point(size=0.3,alpha=0.5) + facet_wrap(~gene,nrow=5) +theme_dark() + 
  coord_fixed() + scale_color
```


```{r plot pairs,fig.height=7,fig.width=9}
jpoint <- function(ga,gb,legend=TRUE){
  expr <- cbind(mat[,normc$ext_gene == ga],mat[,normc$ext_gene == gb]) %>% 
    as_tibble(.,rownames = "cell") %>% rename(!!ga:= V1, !!gb:= V2) %>%
    mutate(cluster=lab.POI)
  g1 <- ggplot(expr,aes(x=!!ensym(ga),y=!!ensym(gb),col=cluster)) + 
    geom_point(alpha=0.7,size=0.3) + theme_minimal()
  if(legend==FALSE) g1 <- g1 + theme(legend.position = 'none')
  return(g1)
}

patchwork::wrap_plots(
  jpoint("Crip2","Ifitm2"),
  jpoint("Map1b","Slfn2"),
  jpoint("Des", "Rpl18a"),
  jpoint("Spats2l","Stmn2"),
  guides = 'collect',nrow=2
)
```

