---
title: "Extraction of DFCs from expreimental data"
output:
  html_notebook:
    theme: united
    toc: yes
  html_document:
    df_print: paged
    theme: united
    toc: yes
  pdf_document: default
---


## Setup

```{r setup}
library(dplyr)
library(ggplot2)

scale_color <- viridis::scale_color_viridis()
discrete_color <- ggsci::scale_color_d3("category20")
```


## calassification & visualization

```{r classification}
quant.test <-  Normc[useg,][useg.30,][B$weight[-1]!=0,] %>% split(.,rownames(Normc[useg,][useg.30,][B$weight[-1]!=0,])) %>% 
  lapply(function(x){as_tibble(t(x)) %>% dplyr::mutate(cluster=Df$cluster)}) %>% 
  lapply(function(x){
    df <- x; colnames(df)[1] <- "value"
    group_by(df,cluster) %>% summarise("1st"=quantile(value)[2],
                                        "mean"=quantile(value)[3],
                                        "3rd"=quantile(value)[4],.groups='drop')
    })
pat.test <- vector("list",3)
names(pat.test) <- c("strong","weak","specific")
for (i in 1:length(quant.test)) {
  if(all(quant.test[[i]][,4] == 0)){
    pat.test[["specific"]] <- c(pat.test[["specific"]],names(quant.test)[i])
    }else{
      if(sum(quant.test[[i]][,4] > 0) < 3 && any(quant.test[[1]]$cluster[quant.test[[1]][,4] > 0] == POI)){
        pat.test[["strong"]] <- c(pat.test[["strong"]],names(quant.test)[i])
        }else{
          pat.test[["weak"]] <- c(pat.test[["weak"]],names(quant.test)[i])
        } 
    }
}

print(pat.test)
lapply(pat.test, length)
```


```{r venn plot}
venn(list(nonDEGs=setdiff(dfcs,res$ext_gene),
          DFCspecific=pat.test$specific))
res[order(res$baseMean),] %>% mutate(baseMean_rank=1:nrow(res)) %>% filter(ext_gene %in% pat.test$specific)
intersect(setdiff(dfcs,res$ext_gene),pat.test$specific)
```


```{r box plot,fig.width=9, fig.height=8}
dfc.expr <- normc %>%
  inner_join(Wei,.,by="ext_gene") %>% 
  tidyr::gather(cell,expr,-(1:4)) %>% inner_join(Df,by="cell")
boxes <- function(x,nrow=5){
  dfc.expr %>%
    filter(ext_gene %in% x) %>%
    ggplot(aes(x=cluster,y=expr,fill=Target)) +
    geom_boxplot() + facet_wrap(~reorder(ext_gene,-abs(weight)),nrow=nrow) +
    theme_minimal() + discrete_color + 
    theme(axis.text.x = element_blank(),legend.position = 'none') 
}
1:3 %>% map(~boxes(pat.test[[.]][1:20]))
#1:3 %>% map(~boxes(pat.test[[.]][1:8],nrow=2)) %>% patchwork::wrap_plots(nrow=3,guides = 'collect')
```


```{r GO enrichment, fig.width=8,fig.height=4}
entid <- bitr(e2g$ens_gene[e2g$ext_gene %in% pat.test$strong],fromType = "ENSEMBL",toType = "ENTREZID",org.Mm.eg.db) %>% .$ENTREZID
goen <- enrichGO(entid,OrgDb = org.Mm.eg.db,readable = TRUE,ont="BP") %>% clusterProfiler::simplify()
dotplot(goen)
```


```{r plot DFC specific, fig.width=10, fig.height=7}
lab.POI <- Df$cluster == POI

set.seed(10)
um.mini <- uwot::umap(t(normc[,-1][,lab.POI]),n_neighbors=30,min_dist=0.5,pca=50,n_threads = 16)
Df.mini <- Df %>% filter(lab.POI) %>% select(c(-UMAP1,-UMAP2)) %>% mutate(UMAP1=um.mini[,1],UMAP2=um.mini[,2],)
expr.spe <- Normc[rownames(Normc) %in% pat.test$specific,] %>% t 
biexpr.spe <- cbind(um.mini,(expr.spe[lab.POI,] >0 )) %>% as_tibble() %>% 
  rename(UMAP1=V1,UMAP2=V2) %>% gather(key="gene",value = "expression",-(1:2))

ggplot(biexpr.spe,aes(x=UMAP1,y=UMAP2,color=as.double(expression))) +
    geom_point(size=0.2,alpha=0.8) + facet_wrap(~gene,nrow = 4) +
    theme_dark() + coord_fixed() + scale_color
patchwork::wrap_plots(
  ggplot(Df.mini,aes(x=UMAP1,y=UMAP2,color=cell_annotation)) +geom_point(size=0.8,alpha=0.8) + theme_minimal() + coord_fixed() + discrete_color,
  ggplot(Df.mini,aes(x=UMAP1,y=UMAP2,color=injury)) +geom_point(size=0.8,alpha=0.8) + theme_minimal() + coord_fixed() + discrete_color,
  ggplot(Df.mini,aes(x=UMAP1,y=UMAP2,color=nUMI)) +geom_point(size=0.8,alpha=0.8) + theme_minimal() + coord_fixed() + scale_color,
  ggplot(Df.mini,aes(x=UMAP1,y=UMAP2,color=percent_mito)) +geom_point(size=0.8,alpha=0.8) + theme_minimal() + coord_fixed() + scale_color,
  ncol=2)
```

```{r plot strong, fig.width=12, fig.height=8}
expr.str <- Normc[rownames(Normc) %in% pat.test$strong,] %>% t 
expr.str <- cbind(um.mini,expr.str[lab.POI,]) %>% as_tibble() %>% rename(UMAP1=V1,UMAP2=V2) %>% gather(key="gene",value = "expression",-(1:2))
expr.str$expression[expr.str$expression > 2.5] <- 2.5 #upper limit = 2.5
ggplot(expr.str,aes(x=UMAP1,y=UMAP2,color=as.double(expression))) +
  geom_point(size=0.3,alpha=0.5) + facet_wrap(~gene,nrow=5) +theme_dark() + 
  coord_fixed() + scale_color
```


```{r lda scoring}
c.dfc <- pat.test$weak %>% unlist(use.names = FALSE) %>% combn(.,2) %>% t %>% as_tibble() %>% rename(gene.x=V1,gene.y=V2)
ldas <- vector(mode = "list",length = nrow(c.dfc))
for (i in 1:nrow(c.dfc)) {
  ga <- c.dfc$gene.x[i]; gb <- c.dfc$gene.y[i]
  a <- cbind(mat[,normc$ext_gene == ga],mat[,normc$ext_gene == gb]) %>% 
    as_tibble(.,row.names = cell) %>% rename(!!ga:= V1, !!gb:= V2)
  ldas[[i]] <- MASS::lda(a,as.factor(lou_$membership) == POI)
}
sing <- ldas %>% lapply(function(x){x$svd}) %>% unlist %>% mutate(c.dfc,SVD=.)
wei <- Wei %>% filter(ext_gene!="Int") %>% .[order(abs(.$weight),decreasing = TRUE),] %>% mutate(wrank=1:(nrow(Wei)-1))
tab <- sing %>% 
  inner_join(.,wei[,-(2:3)],by=c("gene.x"="ext_gene")) %>% inner_join(.,wei[,-(2:3)],by=c("gene.y"="ext_gene")) %>%
  mutate(value=SVD/((weight.x^2)+(weight.y^2)),number=(1:nrow(c.dfc))) %>% .[order(.$value,decreasing = TRUE),]
print(tab)
```

```{r plot pairs,fig.height=10,fig.width=12}
point.weak <- function(i,legend=TRUE){
  ga <- c.dfc$gene.x[i]; gb <- c.dfc$gene.y[i]
  expr <- cbind(mat[,normc$ext_gene == ga],mat[,normc$ext_gene == gb]) %>% 
    as_tibble(.,rownames = "cell") %>% rename(!!ga:= V1, !!gb:= V2) %>%
    mutate(cluster=as.factor(lou_$membership==POI))
  g1 <- ggplot(expr,aes(x=!!ensym(ga),y=!!ensym(gb),col=cluster)) + 
    geom_point(alpha=0.7,size=0.3) + theme_minimal()
  if(legend==FALSE) g1 <- g1 + theme(legend.position = 'none')
  return(g1)
}
multi.point <- function(x){tab$number[x] %>% map(~point.weak(.)) %>% patchwork::wrap_plots(.,guides = 'collect')}
seq(1,nrow(tab),by=16) %>% lapply(function(x) x:(x+15)) %>% .[1:10] %>% map(~multi.point(.))
```

```{r plot pairs2,fig.height=10,fig.width=12}
seq(1,nrow(tab),by=16) %>% lapply(function(x) x:(x+15)) %>% .[11:20] %>% map(~multi.point(.))
```

```{r plot pairs3,fig.height=10,fig.width=12}
seq(1,nrow(tab),by=16) %>% lapply(function(x) x:(x+15)) %>% .[21:30] %>% map(~multi.point(.))
```

```{r plot pairs4,fig.height=10,fig.width=12}
seq(1,nrow(tab),by=16) %>% lapply(function(x) x:(x+15)) %>% .[31:40] %>% map(~multi.point(.))
```

```{r poster_fig}
p1 <- ggplot(Df,aes(x=UMAP1,y=UMAP2,colour=Target)) + geom_point(size=0.15,alpha=0.8) + theme_minimal() + coord_fixed() 
p1_ <- p1 + theme(legend.position = 'none', axis.title = element_blank(), axis.ticks = element_blank(), axis.text = element_blank())
p2 <- ggplot(Df,aes(x=UMAP1,y=UMAP2,colour=cluster)) + geom_point(size=0.15,alpha=0.8) + theme_minimal() + coord_fixed() + discrete_color
p2_ <- p2 + theme(legend.position = 'none', axis.title = element_blank(), axis.ticks = element_blank(), axis.text = element_blank())
p2l <- p2 %>% ggplotGrob() %>% gtable::gtable_filter(., pattern = "guide-box") #%>% grid::grid.draw(.)

box_m <- function(x){dfc.expr %>%
    filter(ext_gene %in% x) %>%
    ggplot(aes(x=cluster,y=expr,fill=Target)) +
    geom_boxplot() + facet_wrap(~reorder(ext_gene,-abs(weight)),nrow=3) +
    ggsci::scale_color_d3("category20") + theme_minimal() +　ylim(0,5) +
    theme(axis.text.x = element_blank(),legend.position = 'none') }
p4 <- box_m("Cdh15")
p5 <- box_m("Calcr")
p6 <- box_m("Crip2")
p7 <- box_m("Ifitm2")

p8 <- dotplot(goen)
p9 <- ggplot(expr[expr$gene %in% pat.test$specific[c(1,2,4,11,8,6)],],aes(x=UMAP1,y=UMAP2,color=as.double(expression))) +
  geom_point(size=0.08,alpha=0.5) + facet_wrap(~gene,nrow = 2) +
  theme_dark() + coord_fixed() + scale_color + theme(legend.position = 'none', axis.title = element_blank(), axis.ticks = element_blank(), axis.text = element_blank())
p12 <- ggplot(res_,aes(x=log2FoldChange,y=log10FDR,color=class)) + geom_point(size=0.4,alpha=0.8) + theme_minimal() + scale_color_manual(values = c("#D62728FF","#808080")) 
p13 <- ggplot(res_,aes(x=baseMean,y=log2FoldChange,color=class)) + geom_point(size=0.1,alpha=0.8) + theme_minimal() + scale_color_manual(values = c("#D62728FF","#808080")) + scale_x_log10()+ theme(legend.position = 'none', axis.title = element_blank(), axis.ticks = element_blank(), axis.text = element_blank())
p14 <- Df %>% cbind(.,t(Normc[rownames(Normc) %in% c("Pax7","Myod1"),])) %>% 
  ggplot(aes(x=UMAP1,y=UMAP2,color=Pax7)) + geom_point(size=0.15,alpha=0.8) + theme_minimal() + scale_color
p14_ <- p14 + theme(legend.position = 'none', axis.title = element_blank(), axis.ticks = element_blank(), axis.text = element_blank())
p14l <- p14 %>% ggplotGrob() %>% gtable::gtable_filter(., pattern = "guide-box")
p15 <- Df %>% cbind(.,t(Normc[rownames(Normc) %in% c("Pax7","Myod1","Myf5"),])) %>% 
  ggplot(aes(x=UMAP1,y=UMAP2,color=Myod1)) + geom_point(size=0.15,alpha=0.8) + theme_minimal() + scale_color
p15_ <- p15 + theme(legend.position = 'none', axis.title = element_blank(), axis.ticks = element_blank(), axis.text = element_blank())
p15l <- p15 %>% ggplotGrob() %>% gtable::gtable_filter(., pattern = "guide-box") 

ggsave(file = "~/fuji/work/Logireg/paper/fig1.jpg", plot = p1_,width=2.7,height=2.5,dpi=300)
ggsave(file = "~/fuji/work/Logireg/paper/fig2.jpg", plot = p2_, width=2.7,height=2.5,dpi=300)
ggsave(file = "~/fuji/work/Logireg/paper/fig2l.pdf", plot = p2l)
ggsave(file = "~/fuji/work/Logireg/paper/fig4.pdf", plot = p4, units = "in", width = 5, height = 4)
ggsave(file = "~/fuji/work/Logireg/paper/fig5.pdf", plot = p5, units = "in", width = 5, height = 4)
ggsave(file = "~/fuji/work/Logireg/paper/fig6.pdf", plot = p6, units = "in", width = 5, height = 4)
ggsave(file = "~/fuji/work/Logireg/paper/fig7.pdf", plot = p7, units = "in", width = 5, height = 4)
ggsave(file = "~/fuji/work/Logireg/paper/fig8.pdf", plot = p8, units = "in", width = 9, height = 4.5)
ggsave(file = "~/fuji/work/Logireg/paper/fig9.jpg", plot = p9,dpi=300, width=5,height=3)
#ggsave(file = "~/fuji/work/Logireg/poster/fig9.pdf", plot = p9, units = "in", width = 5, height = 4)
#ggsave(file = "~/fuji/work/Logireg/paper/fig11.jpg", plot = p11,width=5,height=4,dpi=300)
ggsave(file = "~/fuji/work/Logireg/paper/fig12.jpg", plot = p12, width=4,height=2,dpi=300)
ggsave(file = "~/fuji/work/Logireg/paper/fig13.jpg", plot = p13, width=3,height=2,dpi=300)
ggsave(file = "~/fuji/work/Logireg/paper/fig14.jpg", plot = p14_,width=2.7,height=2.5,dpi=300)
ggsave(file = "~/fuji/work/Logireg/paper/fig14l.pdf", plot = p14l)
ggsave(file = "~/fuji/work/Logireg/paper/fig15.jpg", plot = p15_,width=2.7,height=2.5,dpi=300)
ggsave(file = "~/fuji/work/Logireg/paper/fig15l.pdf", plot = p15l)
```


