---
title: "STRING"
output: html_notebook
---


Downloaded at: <https://string-db.org/cgi/download?species_text=Mus+musculus>

```{r setup}
library(dplyr)
library(tidygraph)
library(ggraph)
```

```{r loadGenes}
#dfc<- readr::read_csv("/DFC/real_data/genelist/dfcs.csv")
#deg <- readr::read_csv("/DFC/real_data/genelist/degs.csv")
```

```{r loadSTRING}
st_link <- readr::read_delim("https://stringdb-static.org/download/protein.links.full.v11.0/10090.protein.links.full.v11.0.txt.gz",delim=" ")
st_info <- readr::read_tsv("https://stringdb-static.org/download/protein.info.v11.0/10090.protein.info.v11.0.txt.gz",col_types="cc__") %>%
  with(setNames(preferred_name,protein_external_id))
stg <- st_link %>% mutate_at(1:2,~st_info[.])
g <- as_tbl_graph(stg,directed=FALSE) %>% rename(gene=name) %E>% distinct
```

```{r subgraph}
dfc_ <- dfc %>% rename(gene=ext_gene)
g_dfc <- g %N>% inner_join(.,dfc,by=c('gene'='ext_gene')) %>% mutate(sgn=if_else(weight>0,"+","-"))
g_deg <- deg %>% top_n(108,abs(stat)) %>% inner_join(activate(g,nodes),.,by=c('gene'='ext_gene')) %>%
  mutate(weight=log2FoldChange,sgn=ifelse(log2FoldChange>0,"+","-"))
```

```{r}
plotg <- function(g, cond){
  g %E>% filter(!!cond) %N>% filter(centrality_degree()>0) %>%
  ggraph(layout="fr") + geom_edge_link(width=0.1) + 
    geom_node_point(aes(size=abs(weight),color=sgn)) +
    geom_node_text(aes(label=gene),repel=TRUE,color="grey20") +
    scale_color_manual(values = c("#F8766D","#00BFC4","#32cd32")) +
    #ggsci::scale_color_aaas() +
    #scale_color_gradient2(high="red",mid="grey",low="blue")+
    theme_void()
}
```

```{r plots, fig.width=7, fig.height=4}
cond <- quo(combined_score>400)
#cond <- quo(coexpression>0 | coexpression_transferred>0)
#cond <- quo(experiments>0 | experiments_transferred>0)
plotg(g_dfc,cond)
plotg(g_deg,cond)
```




